### ISSUE TITLE
Incorporate Instagrams API to link to the hashtags and then display a feed for them!

### ISSUE THREAD

**Issue by huntertwebster** [huntertwebster/many-murals#28]

**Comment by booherbg** [comment]
How do you want to manage content? Maybe a whitelist or blacklist?

Whitelist -- manually approve all images to show before showing them on the page
Blacklist -- show all instagram posts, and hide ones that are bad

Both require a new table and some filtering, kind of depends on how you want to manage it and risk tolerance for abuse.

**Comment by huntertwebster** [comment]
whitelisting > blacklisting 

i wouldn't mind approving them because i will already be approving those who want to make an account to post things too.
