### ISSUE TITLE
ability to add an image when creating a post

### ISSUE THREAD

**Issue by huntertwebster** [huntertwebster/many-murals#33]
- cloudinary post for single and multiple images

**Comment by booherbg** [comment]
Images are a core part of the project. Could be worth exploring Amazon S3 or storing images natively.

Is there anything to store other than, for example, artists / admins uploading actual images of murals? Are there other images, like user images / profile pictures / etc?

**Comment by huntertwebster** [comment]
there are profile pictures which are the also the artists picture on the 'our artists' page

**Comment by huntertwebster** [comment]
by native storage- do you mean on the hosting service?

**Comment by huntertwebster** [comment]
also @booherbg just briefly looked into Amazon S3 and i think the free tier would be enough for what we need.
