### ISSUE TITLE
DB Seed File

### ISSUE THREAD

**Issue by booherbg** [huntertwebster/many-murals#44]
Is there a database seed file that already has images / artists / users set up for easy testing?

**Comment by huntertwebster** [comment]
there's one that exists but it's on my local machine. i'll upload one tonight with all the information needed

**Comment by huntertwebster** [comment]
turns out DB seed isn't as easy as 1, 2, 3. need to look into it more over the next day. in the mean time @booherbg there is fake tester data you can use in the database.sql file that can be used on your local machine
